resolver: lts-12.10

packages:
# The following packages have been ignored due to incompatibility with the
# resolver compiler, dependency conflicts with other packages
# or unsatisfied dependencies.
- .

extra-deps:
